### ISSUE TITLE
条码组件预览时无法显示

### ISSUE THREAD

**Issue by wison-wu** [wison-wu/formDesigner3#11]
RT
![image](https://github.com/wison-wu/formDesigner3/assets/4989545/117f0e5d-2884-4658-8e41-0ef8b53023dc)

**Comment by brizer** [comment]
我是抖音、哔哩哔哩、头条、微信视频号技术工具up主brizer，看到你的产品很好，想给你做个帮推，需要的话加vx：brizer1992，备注产品名。一到两位数rmb换四位到五位数曝光量。
